Swap to using the old -install and -list-remote
The tfenv ones are very specific to Terraform's repos. Hopefully the
removal of tons of shell boilerplate doesn't have too much impact.

Also `s/TFENV/TGENV/g`.

diff --git a/bin/terragrunt b/bin/terragrunt
--- a/bin/terragrunt
+++ b/bin/terragrunt
@@ -10,46 +10,46 @@ function early_death() {
   exit 1;
 };
 
-if [ -z "${TFENV_ROOT:-""}" ]; then
+if [ -z "${TGENV_ROOT:-""}" ]; then
   # http://stackoverflow.com/questions/1055671/how-can-i-get-the-behavior-of-gnus-readlink-f-on-a-mac
   readlink_f() {
     local target_file="${1}";
     local file_name;
 
     while [ "${target_file}" != "" ]; do
-      cd "${target_file%/*}" || early_death "Failed to 'cd \$(${target_file%/*})' while trying to determine TFENV_ROOT";
-      file_name="${target_file##*/}" || early_death "Failed to '\"${target_file##*/}\"' while trying to determine TFENV_ROOT";
+      cd "${target_file%/*}" || early_death "Failed to 'cd \$(${target_file%/*})' while trying to determine TGENV_ROOT";
+      file_name="${target_file##*/}" || early_death "Failed to '\"${target_file##*/}\"' while trying to determine TGENV_ROOT";
       target_file="$(readlink "${file_name}")";
     done;
 
     echo "$(pwd -P)/${file_name}";
   };
-  TFENV_SHIM=$(readlink_f "${0}")
-  TFENV_ROOT="${TFENV_SHIM%/*/*}";
-  [ -n "${TFENV_ROOT}" ] || early_death "Failed to determine TFENV_ROOT";
+  TGENV_SHIM=$(readlink_f "${0}")
+  TGENV_ROOT="${TGENV_SHIM%/*/*}";
+  [ -n "${TGENV_ROOT}" ] || early_death "Failed to determine TGENV_ROOT";
 else
-  TFENV_ROOT="${TFENV_ROOT%/}";
+  TGENV_ROOT="${TGENV_ROOT%/}";
 fi;
-export TFENV_ROOT;
+export TGENV_ROOT;
 
-if [ -n "${TFENV_HELPERS:-""}" ]; then
-  log 'debug' 'TFENV_HELPERS is set, not sourcing helpers again';
+if [ -n "${TGENV_HELPERS:-""}" ]; then
+  log 'debug' 'TGENV_HELPERS is set, not sourcing helpers again';
 else
-  [ "${TFENV_DEBUG:-0}" -gt 0 ] && >&2 echo "[DEBUG] Sourcing helpers from ${TFENV_ROOT}/lib/helpers.sh";
-  if source "${TFENV_ROOT}/lib/helpers.sh"; then
+  [ "${TGENV_DEBUG:-0}" -gt 0 ] && >&2 echo "[DEBUG] Sourcing helpers from ${TGENV_ROOT}/lib/helpers.sh";
+  if source "${TGENV_ROOT}/lib/helpers.sh"; then
     log 'debug' 'Helpers sourced successfully';
   else
-    early_death "Failed to source helpers from ${TFENV_ROOT}/lib/helpers.sh";
+    early_death "Failed to source helpers from ${TGENV_ROOT}/lib/helpers.sh";
   fi;
 fi;
 
 # Ensure libexec and bin are in $PATH
 for dir in libexec bin; do
   case ":${PATH}:" in
-    *:${TFENV_ROOT}/${dir}:*) log 'debug' "\$PATH already contains '${TFENV_ROOT}/${dir}', not adding it again";;
+    *:${TGENV_ROOT}/${dir}:*) log 'debug' "\$PATH already contains '${TGENV_ROOT}/${dir}', not adding it again";;
     *)
-      log 'debug' "\$PATH does not contain '${TFENV_ROOT}/${dir}', prepending and exporting it now";
-      export PATH="${TFENV_ROOT}/${dir}:${PATH}";
+      log 'debug' "\$PATH does not contain '${TGENV_ROOT}/${dir}', prepending and exporting it now";
+      export PATH="${TGENV_ROOT}/${dir}:${PATH}";
       ;;
   esac;
 done;
@@ -60,6 +60,6 @@ done;
 
 log 'debug' "program=\"${0##*/}\"";
 
-declare tfenv_path="${TFENV_ROOT}/bin/tgenv";
+declare tfenv_path="${TGENV_ROOT}/bin/tgenv";
 
 tgenv-exec "$@";
diff --git a/libexec/tgenv-install b/libexec/tgenv-install
--- a/libexec/tgenv-install
+++ b/libexec/tgenv-install
@@ -10,46 +10,46 @@ function early_death() {
   exit 1;
 };
 
-if [ -z "${TFENV_ROOT:-""}" ]; then
+if [ -z "${TGENV_ROOT:-""}" ]; then
   # http://stackoverflow.com/questions/1055671/how-can-i-get-the-behavior-of-gnus-readlink-f-on-a-mac
   readlink_f() {
     local target_file="${1}";
     local file_name;
 
     while [ "${target_file}" != "" ]; do
-      cd "$(dirname ${target_file})" || early_death "Failed to 'cd \$(dirname ${target_file})' while trying to determine TFENV_ROOT";
-      file_name="$(basename "${target_file}")" || early_death "Failed to 'basename \"${target_file}\"' while trying to determine TFENV_ROOT";
+      cd "$(dirname ${target_file})" || early_death "Failed to 'cd \$(dirname ${target_file})' while trying to determine TGENV_ROOT";
+      file_name="$(basename "${target_file}")" || early_death "Failed to 'basename \"${target_file}\"' while trying to determine TGENV_ROOT";
       target_file="$(readlink "${file_name}")";
     done;
 
     echo "$(pwd -P)/${file_name}";
   };
 
-  TFENV_ROOT="$(cd "$(dirname "$(readlink_f "${0}")")/.." && pwd)";
-  [ -n "${TFENV_ROOT}" ] || early_death "Failed to 'cd \"\$(dirname \"\$(readlink_f \"${0}\")\")/..\" && pwd' while trying to determine TFENV_ROOT";
+  TGENV_ROOT="$(cd "$(dirname "$(readlink_f "${0}")")/.." && pwd)";
+  [ -n "${TGENV_ROOT}" ] || early_death "Failed to 'cd \"\$(dirname \"\$(readlink_f \"${0}\")\")/..\" && pwd' while trying to determine TGENV_ROOT";
 else
-  TFENV_ROOT="${TFENV_ROOT%/}";
+  TGENV_ROOT="${TGENV_ROOT%/}";
 fi;
-export TFENV_ROOT;
+export TGENV_ROOT;
 
-if [ -n "${TFENV_HELPERS:-""}" ]; then
-  log 'debug' 'TFENV_HELPERS is set, not sourcing helpers again';
+if [ -n "${TGENV_HELPERS:-""}" ]; then
+  log 'debug' 'TGENV_HELPERS is set, not sourcing helpers again';
 else
-  [ "${TFENV_DEBUG:-0}" -gt 0 ] && echo "[DEBUG] Sourcing helpers from ${TFENV_ROOT}/lib/helpers.sh";
-  if source "${TFENV_ROOT}/lib/helpers.sh"; then
+  [ "${TGENV_DEBUG:-0}" -gt 0 ] && echo "[DEBUG] Sourcing helpers from ${TGENV_ROOT}/lib/helpers.sh";
+  if source "${TGENV_ROOT}/lib/helpers.sh"; then
     log 'debug' 'Helpers sourced successfully';
   else
-    early_death "Failed to source helpers from ${TFENV_ROOT}/lib/helpers.sh";
+    early_death "Failed to source helpers from ${TGENV_ROOT}/lib/helpers.sh";
   fi;
 fi;
 
 # Ensure libexec and bin are in $PATH
 for dir in libexec bin; do
   case ":${PATH}:" in
-    *:${TFENV_ROOT}/${dir}:*) log 'debug' "\$PATH already contains '${TFENV_ROOT}/${dir}', not adding it again";;
+    *:${TGENV_ROOT}/${dir}:*) log 'debug' "\$PATH already contains '${TGENV_ROOT}/${dir}', not adding it again";;
     *)
-      log 'debug' "\$PATH does not contain '${TFENV_ROOT}/${dir}', prepending and exporting it now";
-      export PATH="${TFENV_ROOT}/${dir}:${PATH}";
+      log 'debug' "\$PATH does not contain '${TGENV_ROOT}/${dir}', prepending and exporting it now";
+      export PATH="${TGENV_ROOT}/${dir}:${PATH}";
       ;;
   esac;
 done;
@@ -58,230 +58,76 @@ done;
 # Begin Script Body #
 #####################
 
-[ "${#}" -gt 1 ] && log 'error' 'usage: tgenv install [<version>]';
+#!/usr/bin/env bash
 
-declare requested="${1:-""}";
+[ -n "${TGENV_DEBUG}" ] && set -x
+source "${TGENV_ROOT}/libexec/helpers"
 
-log debug "Resolving version with: tgenv-resolve-version ${requested}";
-declare resolved;
-resolved="$(tgenv-resolve-version ${requested})" || log 'error' "Failed to resolve ${requested} version";
+[ "${#}" -gt 1 ] && error_and_die "usage: tgenv install [<version>]"
 
-declare version="${resolved%%\:*}";
-declare regex="${resolved##*\:}";
+declare version_requested version regex
 
-[ -n "${version}" ] || log 'error' 'Version is not specified. This should not be possible as we default to latest';
+if [ -z "${1}" ]; then
+  version_file="$(tgenv-version-file)"
+  if [ "${version_file}" != "${TGENV_ROOT}/version" ]; then
+    version_requested="$(cat "${version_file}" || true)"
+  fi
+else
+  version_requested="${1}"
+fi
 
-log 'debug' "Processing install for version ${version}, using regex ${regex}";
+if [[ "${version_requested}" =~ ^latest\:.*$ ]]; then
+  version="${version_requested%%\:*}"
+  regex="${version_requested##*\:}"
+elif [[ "${version_requested}" =~ ^latest$ ]]; then
+  version="${version_requested}"
+  regex="^[0-9]\+\.[0-9]\+\.[0-9]\+$"
+else
+  version="${version_requested}"
+  regex="^${version_requested}$"
+fi
 
-remote_version="$(tgenv-list-remote | grep -e "${regex}" | head -n 1)";
-[ -n "${remote_version}" ] && version="${remote_version}" || log 'error' "No versions matching '${requested:-$version}' found in remote";
+[ -n "${version}" ] || error_and_die "Version is not specified"
+version="$(tgenv-list-remote | grep -e "${regex}" | head -n 1)"
+[ -n "${version}" ] || error_and_die "No versions matching '${1}' found in remote"
 
-dst_path="${TFENV_CONFIG_DIR}/versions/${version}";
+dst_path="${TGENV_ROOT}/versions/${version}"
 if [ -f "${dst_path}/terragrunt" ]; then
-  echo "Terragrunt v${version} is already installed";
-  exit 0;
-fi;
+  echo "Terragrunt v${version} is already installed"
+  exit 0
+fi
 
-# Add support of ARM64 for Linux & Apple Silicon
-case "$(uname -m)" in
-  aarch64* | arm64*)
-    # There is no arm64 support for versions:
-    # < 0.11.15
-    # >= 0.12.0, < 0.12.30
-    # >= 0.13.0, < 0.13.5
-    if [[ "${version}" =~ 0\.(([0-9]|10))\.\d* ||
-          "${version}" =~ 0\.11\.(([0-9]|1[0-4]))$ ||
-          "${version}" =~ 0\.12\.(([0-9]|[1-2][0-9]))$ ||
-          "${version}" =~ 0\.13\.[0-4]$
-    ]]; then
-      TFENV_ARCH="${TFENV_ARCH:-amd64}";
-    else
-      TFENV_ARCH="${TFENV_ARCH:-arm64}";
-    fi;
-    ;;
-  *)
-    TFENV_ARCH="${TFENV_ARCH:-amd64}";
-    ;;
-esac;
-
+TGENV_ARCH="${TGENV_ARCH:-amd64}"
 case "$(uname -s)" in
   Darwin*)
-    os="darwin_${TFENV_ARCH}";
+    os="darwin_${TGENV_ARCH}"
     ;;
   MINGW64*)
-    os="windows_${TFENV_ARCH}";
+    os="windows_${TGENV_ARCH}"
     ;;
   MSYS_NT*)
-    os="windows_${TFENV_ARCH}";
+    os="windows_${TGENV_ARCH}"
     ;;
   CYGWIN_NT*)
-    os="windows_${TFENV_ARCH}";
-    ;;
-  FreeBSD*)
-    os="freebsd_${TFENV_ARCH}";
+    os="windows_${TGENV_ARCH}"
     ;;
   *)
-    os="linux_${TFENV_ARCH}";
+    os="linux_${TGENV_ARCH}"
     ;;
-esac;
+esac
 
-keybase_bin="$(command -v keybase 2>/dev/null)";
-shasum_bin="$(command -v shasum 2>/dev/null)";
-sha256sum_bin="$(command -v sha256sum 2>/dev/null)";
+version_url="https://github.com/gruntwork-io/terragrunt/releases/download/v${version}"
 
-TFENV_REMOTE="${TFENV_REMOTE:-https://releases.hashicorp.com}";
-version_url="${TFENV_REMOTE}/terragrunt/${version}";
+tarball_name="terragrunt_${os}";
 
-# Thanks for the inconsistency in 0.12-alpha, Hashicorp(!)
-if [[ "${version}" =~ 0.12.0-alpha[3-9] ]]; then
-  tarball_name="terragrunt_${version}_terragrunt_${version}_${os}.zip";
-else
-  tarball_name="terragrunt_${version}_${os}.zip";
-fi;
+info "Installing Terragrunt v${version}"
 
-shasums_name="terragrunt_${version}_SHA256SUMS";
-shasums_signing_key_postfix=".72D7468F";
-shasums_sig="${shasums_name}${shasums_signing_key_postfix}.sig";
+mkdir -p "${dst_path}" || error_and_die "Failed to make directory ${dst_path}"
 
-log 'info' "Installing Terragrunt v${version}";
+info "Downloading release tarball from ${version_url}/${tarball_name}"
+curlw -# --location-trusted -f -o "${dst_path}/terragrunt" "${version_url}/${tarball_name}" || error_and_die "Tarball download failed"
 
-# Create a local temporary directory for downloads
-tmpdir_arg="-t";
+chmod +x "${dst_path}/terragrunt" || error_and_die "Change rights failed"
 
-if mktemp --help 2>&1 | grep -- '--tmpdir' >/dev/null; then
-  tmpdir_arg="--tmpdir";
-fi;
-
-download_tmp="$(mktemp -d ${tmpdir_arg} tfenv_download.XXXXXX)" || log 'error' "Unable to create temporary download directory (mktemp -d ${tmpdir_arg} tfenv_download.XXXXXX). Working Directory is: $(pwd)";
-
-# Clean it up in case of error
-trap "rm -rf ${download_tmp}" EXIT;
-
-declare curl_progress="";
-case "${TFENV_CURL_OUTPUT:-2}" in
-  '2')
-    log 'debug' 'Setting curl progress bar with "-#"';
-    curl_progress="-#";
-    ;;
-  '1')
-    log 'debug' 'Using default curl output';
-    curl_progress="";
-    ;;
-  '0')
-    log 'debug' 'Running curl silently with "-s"';
-    curl_progress="-s";
-    ;;
-  *)
-    log 'error' 'TFENV_CURL_OUTPUT specified, but not with a supported value ([0,1,2])';
-    ;;
-esac;
-
-log 'info' "Downloading release tarball from ${version_url}/${tarball_name}";
-curlw ${curl_progress} -f -L -o "${download_tmp}/${tarball_name}" "${version_url}/${tarball_name}" || log 'error' 'Tarball download failed';
-log 'info' "Downloading SHA hash file from ${version_url}/${shasums_name}";
-curlw -s -f -L -o "${download_tmp}/${shasums_name}" "${version_url}/${shasums_name}" || log 'error' 'SHA256 hashes download failed';
-
-download_signature() {
-  log 'info' "Downloading SHA hash signature file from ${version_url}/${shasums_sig}";
-  curlw -s -f -L \
-    -o "${download_tmp}/${shasums_sig}" \
-    "${version_url}/${shasums_sig}" \
-    && log 'debug' "SHA256SUMS signature file downloaded successfully to ${download_tmp}/${shasums_sig}" \
-    || log 'error' 'SHA256SUMS signature download failed';
-};
-
-# If on MacOS with Homebrew, use GNU grep
-# This allows keybase login detection to work on Mac,
-# and is required to be able to detect terragrunt version
-# from "required_version" setting in "*.tf" files
-check_dependencies;
-
-# Verify signature if verification mechanism (keybase, gpg, etc) is present
-if [[ -f "${TFENV_CONFIG_DIR}/use-gnupg" ]]; then
-  # GnuPG uses the user's keyring, and any web-of-trust or local signatures or
-  # anything else they have setup.  This is the crazy-powerful mode which is
-  # overly confusing to newcomers.  We don't support it without the user creating
-  # the file use-gnupg, optionally with directives in it.
-  gnupg_command="$(sed -E -n -e 's/^binary: *//p' <"${TFENV_CONFIG_DIR}/use-gnupg")";
-  [[ -n "${gnupg_command}" ]] || gnupg_command=gpg;
-
-  download_signature;
-  # Deliberately unquoted command, in case caller has something fancier in "use-gnupg".
-  # Also, don't use batch mode.  If someone specifies GnuPG, let them deal with any prompting.
-  ${gnupg_command} \
-    --verify "${download_tmp}/${shasums_sig}" \
-    "${download_tmp}/${shasums_name}" \
-    || log 'error' 'PGP signature rejected by GnuPG';
-
-elif [[ -f "${TFENV_CONFIG_DIR}/use-gpgv" ]]; then
-  # gpgv is a much simpler interface to verification, but does require that the
-  # key have been downloaded and marked trusted.
-  # We don't force the caller to trust the tgenv repo's copy of their key, they
-  # have to choose to make that trust decision.
-  gpgv_command="$(sed -E -n -e 's/^binary: *//p' <"${TFENV_CONFIG_DIR}/use-gpgv")";
-  trust_tfenv="$(sed -E -n -e 's/^trust.?tgenv: *//p' <"${TFENV_CONFIG_DIR}/use-gpgv")";
-  [[ -n "${gpgv_command}" ]] || gpgv_command=gpgv;
-
-  download_signature;
-  if [[ "${trust_tfenv}" == 'yes' ]]; then
-    ${gpgv_command} \
-      --keyring "${TFENV_ROOT}/share/hashicorp-keys.pgp" \
-      "${download_tmp}/${shasums_sig}" \
-      "${download_tmp}/${shasums_name}" \
-      || log 'error' 'PGP signature rejected';
-  else
-    ${gpgv_command} \
-      "${download_tmp}/${shasums_sig}" \
-      "${download_tmp}/${shasums_name}" \
-      || log 'error' 'PGP signature rejected';
-  fi;
-elif [[ -n "${keybase_bin}" && -x "${keybase_bin}" ]]; then
-  grep -Eq '^Logged in:[[:space:]]*yes' <("${keybase_bin}" status);
-  keybase_logged_in="${?}";
-  grep -Fq hashicorp <("${keybase_bin}" list-following);
-  keybase_following_hc="${?}";
-
-  if [[ "${keybase_logged_in}" -ne 0 || "${keybase_following_hc}" -ne 0 ]]; then
-    log 'warn' 'Unable to verify OpenPGP signature unless logged into keybase and following hashicorp';
-  else
-    download_signature;
-    "${keybase_bin}" pgp verify \
-      -S hashicorp \
-      -d "${download_tmp}/${shasums_sig}" \
-      -i "${download_tmp}/${shasums_name}" \
-      && log 'debug' 'SHA256SUMS signature matched' \
-      || log 'error' 'SHA256SUMS signature does not match!';
-  fi;
-else
-  # Warning about this avoids an unwarranted sense of confidence in the SHA check
-  log 'warn' "Not instructed to use Local PGP (${TFENV_CONFIG_DIR}/use-{gpgv,gnupg}) & No keybase install found, skipping OpenPGP signature verification";
-fi;
-
-if [[ -n "${shasum_bin}" && -x "${shasum_bin}" ]]; then
-  (
-    cd "${download_tmp}";
-    "${shasum_bin}" \
-      -a 256 \
-      -s \
-      -c <(grep -F "${tarball_name}" "${shasums_name}")
-  ) || log 'error' 'SHA256 hash does not match!';
-elif [[ -n "${sha256sum_bin}" && -x "${sha256sum_bin}" ]]; then
-  (
-    cd "${download_tmp}";
-    "${sha256sum_bin}" \
-      -c <(grep -F "${tarball_name}" "${shasums_name}")
-  ) || log 'error' 'SHA256 hash does not match!';
-else
-  # Lack of shasum deserves a proper warning
-  log 'warn' 'No shasum tool available. Skipping SHA256 hash validation';
-fi;
-
-mkdir -p "${dst_path}" || log 'error' "Failed to make directory ${dst_path}";
-
-declare unzip_output;
-unzip_output="$(unzip -o "${download_tmp}/${tarball_name}" -d "${dst_path}")" || log 'error' 'Tarball unzip failed';
-while IFS= read -r unzip_line; do
- log 'info' "${unzip_line}";
-done < <(printf '%s\n' "${unzip_output}");
-
-log 'info' "Installation of terragrunt v${version} successful. To make this your default version, run 'tgenv use ${version}'";
+info "Installation of terragrunt v${version} successful"
+tgenv-use "${version}"
