actually commit

diff --git a/libexec/tgenv---version b/libexec/tgenv---version
--- a/libexec/tgenv---version
+++ b/libexec/tgenv---version
@@ -1,17 +1,13 @@
 #!/usr/bin/env bash
+# Summary: Display the version of tgenv
 #
-# Summary: Run an executable with the selected Terraform version
+# Displays the version number of this tgenv release, including the
+# current revision from git, if available.
 #
-# Usage: tfenv exec <command> [arg1 arg2...]
-#
-# Runs an executable by first preparing PATH so that the selected Terraform
-# version's `bin' directory is at the front.
-#
-# For example, if the currently selected Terraform version is 0.7.0:
-#   tfenv exec plan
-#
-# is equivalent to:
-#   PATH="$TFENV_ROOT/versions/0.7.0/bin:$PATH" terraform plan
+# The format of the git revision is:
+#   <version>-<num_commits>-<git_sha>
+# where `num_commits` is the number of commits since `version` was
+# tagged.
 
 set -uo pipefail;
 
@@ -72,4 +68,19 @@ done;
 # Begin Script Body #
 #####################
 
-tfenv-exec "$@";
+log 'debug' 'Scraping tgenv version from CHANGELOG.md';
+version="$(awk '/^##/{ print $2; exit}' "${TFENV_ROOT}/CHANGELOG.md")" \
+  && log 'debug' "Found version '${version}' in CHANGELOG.md" \
+  || log 'error' 'Failed to scrape version from CHANGELOG.md';
+
+git_revision="";
+if cd "$(dirname ${0})" 2>/dev/null && git remote -v 2>/dev/null | grep -q tgenv; then
+  log 'debug' 'Git configuration found. Overriding CHANGELOG version from git revision...';
+  git_revision="$(git describe --tags HEAD 2>/dev/null || true)";
+  log 'debug' "Stripping git revision string from ${git_revision}";
+  git_revision="${git_revision#v}";
+fi;
+
+echo "tgenv ${git_revision:-$version}";
+
+exit 0;
diff --git a/libexec/tgenv-list b/libexec/tgenv-list
--- a/libexec/tgenv-list
+++ b/libexec/tgenv-list
@@ -1,5 +1,4 @@
 #!/usr/bin/env bash
-# Summary: Show the currently-selected terraform version
 
 set -uo pipefail;
 
@@ -56,14 +55,56 @@ for dir in libexec bin; do
   esac;
 done;
 
-# If on MacOS with Homebrew, use GNU grep
-# This allows keybase login detection to work on Mac,
-# and is required to be able to detect terraform version
-# from "required_version" setting in "*.tf" files
-check_dependencies;
-
 #####################
 # Begin Script Body #
 #####################
 
-tfenv-version-name "$@";
+[ "${#}" -ne 0 ] \
+  && log 'error' "usage: tgenv list";
+
+[ -d "${TFENV_CONFIG_DIR}/versions" ] \
+  || log 'error' 'No versions available. Please install one with: tgenv install';
+
+[[ -x "${TFENV_CONFIG_DIR}/versions" && -r "${TFENV_CONFIG_DIR}/versions" ]] \
+  || log 'error' "tgenv versions directory is inaccessible: ${TFENV_CONFIG_DIR}/versions";
+
+version_name="$(tgenv-version-name 2>/dev/null || true)" \
+  && log 'debug' "tgenv-version-name reported: ${version_name}";
+export version_name;
+
+if [ -z "${TFENV_Terragrunt_VERSION:-""}" ]; then
+  version_source="$(tgenv-version-file)" \
+    && log 'debug' "tgenv-version-file reported: ${version_source}" \
+    || log 'error' "tgenv-version-file failed";
+else
+  version_source='TFENV_Terragrunt_VERSION';
+fi;
+export version_source;
+
+# Register for whether a default terragrunt version has yet been set
+declare -i default_set=0;
+
+print_version () {
+  if [ "${1}" == "${version_name}" ]; then
+    echo "* ${1} (set by ${version_source})";
+    default_set=1;
+  else
+    echo "  ${1}";
+  fi;
+};
+
+log 'debug' 'Listing versions...';
+local_versions=($(\find "${TFENV_CONFIG_DIR}/versions/" -type d -exec basename {} \; \
+  | tail -n +2 \
+  | sort -t'.' -k 1nr,1 -k 2nr,2 -k 3nr,3));
+
+log 'debug' "Local versions: ${local_versions[@]}";
+
+log 'debug' 'Printing versions...';
+for local_version in ${local_versions[@]}; do
+  print_version "${local_version}";
+done;
+
+[ "${default_set}" -eq 0 ] && log 'info' "No default set. Set with 'tgenv use <version>'";
+
+exit 0;
diff --git a/libexec/tgenv-list-remote b/libexec/tgenv-list-remote
--- a/libexec/tgenv-list-remote
+++ b/libexec/tgenv-list-remote
@@ -1,6 +1,4 @@
 #!/usr/bin/env bash
-# Usage: tfenv version-file
-# Summary: Detect the file that sets the current tfenv version
 
 set -uo pipefail;
 
@@ -20,7 +18,7 @@ if [ -z "${TFENV_ROOT:-""}" ]; then
     local file_name;
 
     while [ "${target_file}" != "" ]; do
-      cd "$(dirname ${target_file})" || early_death "Failed to 'cd \$(dirname ${target_file})' while trying to determine TFENV_ROOT";
+      cd "$(dirname "${target_file}")" || early_death "Failed to 'cd \$(dirname ${target_file})' while trying to determine TFENV_ROOT";
       file_name="$(basename "${target_file}")" || early_death "Failed to 'basename \"${target_file}\"' while trying to determine TFENV_ROOT";
       target_file="$(readlink "${file_name}")";
     done;
@@ -61,4 +59,22 @@ done;
 # Begin Script Body #
 #####################
 
-tfenv-version-file "$@";
+if [ "${#}" -ne 0 ];then
+  echo "usage: tgenv list-remote" 1>&2;
+  exit 1;
+fi;
+
+TFENV_REMOTE="${TFENV_REMOTE:-https://releases.hashicorp.com}";
+log 'debug' "TFENV_REMOTE: ${TFENV_REMOTE}";
+
+declare remote_versions;
+remote_versions="$(curlw -sSf "${TFENV_REMOTE}/terragrunt/")" \
+  || log 'error' "Failed to download remote versions from ${TFENV_REMOTE}/terragrunt/";
+
+#log 'debug' "Remote versions available: ${remote_versions}"; # Even in debug mode this is too verbose
+
+if [[ "${TFENV_REVERSE_REMOTE:-0}" -eq 1 ]]; then
+  grep -o -E "[0-9]+\.[0-9]+\.[0-9]+(-(rc|beta|alpha|oci)-?[0-9]*)?" <<<"${remote_versions}" | uniq | awk '{a[i++]=$0} END {for (j=i-1; j>=0;) print a[j--] }';
+else
+  grep -o -E "[0-9]+\.[0-9]+\.[0-9]+(-(rc|beta|alpha|oci)-?[0-9]*)?" <<<"${remote_versions}" | uniq;
+fi;
diff --git a/libexec/tgenv-pin b/libexec/tgenv-pin
--- a/libexec/tgenv-pin
+++ b/libexec/tgenv-pin
@@ -60,18 +60,18 @@ done;
 #####################
 
 [ "${#}" -ne 0 ] \
-  && log 'error' "usage: tfenv pin";
+  && log 'error' "usage: tgenv pin";
 
 [ -d "${TFENV_CONFIG_DIR}/versions/" ] \
-  || log 'error' 'No versions available. Please install one with: tfenv install';
+  || log 'error' 'No versions available. Please install one with: tgenv install';
 
 [[ -x "${TFENV_CONFIG_DIR}/versions" && -r "${TFENV_CONFIG_DIR}/versions" ]] \
-  || log 'error' "tfenv versions directory is inaccessible: ${TFENV_CONFIG_DIR}/versions";
+  || log 'error' "tgenv versions directory is inaccessible: ${TFENV_CONFIG_DIR}/versions";
 
-version_name="$(tfenv-version-name 2>/dev/null || true)" \
-  && log 'debug' "tfenv-version-name reported: ${version_name}";
+version_name="$(tgenv-version-name 2>/dev/null || true)" \
+  && log 'debug' "tgenv-version-name reported: ${version_name}";
 
-echo "${version_name}" > .terraform-version;
-log 'info' "Pinned version by writing \"${version_name}\" to $(pwd)/.terraform-version";
+echo "${version_name}" > .terragrunt-version;
+log 'info' "Pinned version by writing \"${version_name}\" to $(pwd)/.terragrunt-version";
 
 exit 0;
